### ISSUE TITLE
cant start script

### ISSUE THREAD

**Issue by hanselke** [nachomazzara/mautic-api-nodejs#1]
> node dist/index.js

module.js:471
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hanselke/Infrastructure/mautic-api-nodejs/dist/config/constants.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hanselke/Infrastructure/mautic-api-nodejs/dist/routes/auth.js:15:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by sguilly** [comment]
Create config.js based on sample.config.js in the same root

**Comment by hanselke** [comment]
There isn’t a sample.config.js in the root when you clone the repo.
Tried to create one from your docs but it didn’t work

**Comment by sguilly** [comment]
The file is not in root of the project but in src/config
https://github.com/nachomazzara/mautic-api-nodejs/blob/master/src/config/config.sample.js
